import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
import UserProvider from "./context/user";
import CartProvider from "./context/cart";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <UserProvider>
          <CartProvider>

          {children}
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
